//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/ofmendez/DataDocs/Work/Ubuntu/LENGUAJES/Danfab/projectUnity/Danfab/Assets/Antlr4/Fa.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="FaParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface IFaVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="FaParser.principal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrincipal([NotNull] FaParser.PrincipalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] FaParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FaParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_call([NotNull] FaParser.Function_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FaParser.arrayPosition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayPosition([NotNull] FaParser.ArrayPositionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FaParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrint([NotNull] FaParser.PrintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FaParser.arraysize"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArraysize([NotNull] FaParser.ArraysizeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FaParser.if_regular"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_regular([NotNull] FaParser.If_regularContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FaParser.if_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_return([NotNull] FaParser.If_returnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FaParser.if_break_continue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_break_continue([NotNull] FaParser.If_break_continueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FaParser.if_return_break_continue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_return_break_continue([NotNull] FaParser.If_return_break_continueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FaParser.switch_regular"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_regular([NotNull] FaParser.Switch_regularContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FaParser.switch_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_return([NotNull] FaParser.Switch_returnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FaParser.switch_break_continue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_break_continue([NotNull] FaParser.Switch_break_continueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FaParser.switch_return_break_continue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_return_break_continue([NotNull] FaParser.Switch_return_break_continueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FaParser.while_regular"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile_regular([NotNull] FaParser.While_regularContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FaParser.while_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile_return([NotNull] FaParser.While_returnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FaParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] FaParser.FunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>bodyPrint</c>
	/// labeled alternative in <see cref="FaParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBodyPrint([NotNull] FaParser.BodyPrintContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>bodyFunctionCall</c>
	/// labeled alternative in <see cref="FaParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBodyFunctionCall([NotNull] FaParser.BodyFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>bodyAssignVariable</c>
	/// labeled alternative in <see cref="FaParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBodyAssignVariable([NotNull] FaParser.BodyAssignVariableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>bodyArrayPosition</c>
	/// labeled alternative in <see cref="FaParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBodyArrayPosition([NotNull] FaParser.BodyArrayPositionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>bodyArrayDeclaration</c>
	/// labeled alternative in <see cref="FaParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBodyArrayDeclaration([NotNull] FaParser.BodyArrayDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>body_regularBody</c>
	/// labeled alternative in <see cref="FaParser.body_regular"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_regularBody([NotNull] FaParser.Body_regularBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>body_regularIfRegular</c>
	/// labeled alternative in <see cref="FaParser.body_regular"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_regularIfRegular([NotNull] FaParser.Body_regularIfRegularContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>body_regularSwRegular</c>
	/// labeled alternative in <see cref="FaParser.body_regular"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_regularSwRegular([NotNull] FaParser.Body_regularSwRegularContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>body_regularWhileRegular</c>
	/// labeled alternative in <see cref="FaParser.body_regular"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_regularWhileRegular([NotNull] FaParser.Body_regularWhileRegularContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>body_regularEpsilon</c>
	/// labeled alternative in <see cref="FaParser.body_regular"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_regularEpsilon([NotNull] FaParser.Body_regularEpsilonContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>body_returnBody</c>
	/// labeled alternative in <see cref="FaParser.body_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_returnBody([NotNull] FaParser.Body_returnBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>body_returnIfReturn</c>
	/// labeled alternative in <see cref="FaParser.body_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_returnIfReturn([NotNull] FaParser.Body_returnIfReturnContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>body_returnSwitchReturn</c>
	/// labeled alternative in <see cref="FaParser.body_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_returnSwitchReturn([NotNull] FaParser.Body_returnSwitchReturnContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>body_returWhileReturn</c>
	/// labeled alternative in <see cref="FaParser.body_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_returWhileReturn([NotNull] FaParser.Body_returWhileReturnContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>body_returnReturnregular</c>
	/// labeled alternative in <see cref="FaParser.body_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_returnReturnregular([NotNull] FaParser.Body_returnReturnregularContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>body_returnEpsilon</c>
	/// labeled alternative in <see cref="FaParser.body_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_returnEpsilon([NotNull] FaParser.Body_returnEpsilonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FaParser.return_regular"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn_regular([NotNull] FaParser.Return_regularContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>body_BC_Body</c>
	/// labeled alternative in <see cref="FaParser.body_break_continue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_BC_Body([NotNull] FaParser.Body_BC_BodyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>body_BC_IfBC</c>
	/// labeled alternative in <see cref="FaParser.body_break_continue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_BC_IfBC([NotNull] FaParser.Body_BC_IfBCContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>body_BC_SwitchBC</c>
	/// labeled alternative in <see cref="FaParser.body_break_continue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_BC_SwitchBC([NotNull] FaParser.Body_BC_SwitchBCContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>body_BC_WhileRegular</c>
	/// labeled alternative in <see cref="FaParser.body_break_continue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_BC_WhileRegular([NotNull] FaParser.Body_BC_WhileRegularContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>body_BC_BC</c>
	/// labeled alternative in <see cref="FaParser.body_break_continue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_BC_BC([NotNull] FaParser.Body_BC_BCContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>body_BC_Epsilon</c>
	/// labeled alternative in <see cref="FaParser.body_break_continue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_BC_Epsilon([NotNull] FaParser.Body_BC_EpsilonContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>body_RBC_Body</c>
	/// labeled alternative in <see cref="FaParser.body_return_break_continue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_RBC_Body([NotNull] FaParser.Body_RBC_BodyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>body_RBC_IfRBC</c>
	/// labeled alternative in <see cref="FaParser.body_return_break_continue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_RBC_IfRBC([NotNull] FaParser.Body_RBC_IfRBCContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>body_RBC_SwitchRBC</c>
	/// labeled alternative in <see cref="FaParser.body_return_break_continue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_RBC_SwitchRBC([NotNull] FaParser.Body_RBC_SwitchRBCContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>body_RBC_WhileReturn</c>
	/// labeled alternative in <see cref="FaParser.body_return_break_continue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_RBC_WhileReturn([NotNull] FaParser.Body_RBC_WhileReturnContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>body_RBC_BC</c>
	/// labeled alternative in <see cref="FaParser.body_return_break_continue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_RBC_BC([NotNull] FaParser.Body_RBC_BCContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>body_RBC_Return</c>
	/// labeled alternative in <see cref="FaParser.body_return_break_continue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_RBC_Return([NotNull] FaParser.Body_RBC_ReturnContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>body_RBC_Epsilon</c>
	/// labeled alternative in <see cref="FaParser.body_return_break_continue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_RBC_Epsilon([NotNull] FaParser.Body_RBC_EpsilonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] FaParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expressionContentFunctionCall</c>
	/// labeled alternative in <see cref="FaParser.expressionContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionContentFunctionCall([NotNull] FaParser.ExpressionContentFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expressionContentSumOrNeg</c>
	/// labeled alternative in <see cref="FaParser.expressionContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionContentSumOrNeg([NotNull] FaParser.ExpressionContentSumOrNegContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expressionContentRelational</c>
	/// labeled alternative in <see cref="FaParser.expressionContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionContentRelational([NotNull] FaParser.ExpressionContentRelationalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expressionContentequality</c>
	/// labeled alternative in <see cref="FaParser.expressionContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionContentequality([NotNull] FaParser.ExpressionContentequalityContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expressionContentContentOr</c>
	/// labeled alternative in <see cref="FaParser.expressionContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionContentContentOr([NotNull] FaParser.ExpressionContentContentOrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expressionContentID</c>
	/// labeled alternative in <see cref="FaParser.expressionContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionContentID([NotNull] FaParser.ExpressionContentIDContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expressionContentArraySize</c>
	/// labeled alternative in <see cref="FaParser.expressionContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionContentArraySize([NotNull] FaParser.ExpressionContentArraySizeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expressionContentMul</c>
	/// labeled alternative in <see cref="FaParser.expressionContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionContentMul([NotNull] FaParser.ExpressionContentMulContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expressionContentNegative</c>
	/// labeled alternative in <see cref="FaParser.expressionContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionContentNegative([NotNull] FaParser.ExpressionContentNegativeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expressionContentParenthesis</c>
	/// labeled alternative in <see cref="FaParser.expressionContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionContentParenthesis([NotNull] FaParser.ExpressionContentParenthesisContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expressionContentArrayPosition</c>
	/// labeled alternative in <see cref="FaParser.expressionContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionContentArrayPosition([NotNull] FaParser.ExpressionContentArrayPositionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expressionContentAnd</c>
	/// labeled alternative in <see cref="FaParser.expressionContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionContentAnd([NotNull] FaParser.ExpressionContentAndContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expressionContentdataType</c>
	/// labeled alternative in <see cref="FaParser.expressionContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionContentdataType([NotNull] FaParser.ExpressionContentdataTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expressionContentNot</c>
	/// labeled alternative in <see cref="FaParser.expressionContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionContentNot([NotNull] FaParser.ExpressionContentNotContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FaParser.dataType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDataType([NotNull] FaParser.DataTypeContext context);
}
